In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [8]:
data = pd.read_csv('datasets/datos_abiertos_covid19/200610COVID19MEXICO.csv', encoding='utf8', sep=',')

In [10]:
data.tail()

,FECHA_ACTUALIZACION,ID_REGISTRO,ORIGEN,SECTOR,ENTIDAD_UM,SEXO,ENTIDAD_NAC,ENTIDAD_RES,MUNICIPIO_RES,TIPO_PACIENTE,...,CARDIOVASCULAR,OBESIDAD,RENAL_CRONICA,TABAQUISMO,OTRO_CASO,RESULTADO,MIGRANTE,PAIS_NACIONALIDAD,PAIS_ORIGEN,UCI
369357,2020-06-10,081dda,2,12,15,2,99,9,14,1,...,2,2,2,2,1,3,2,Bolivia,99,97
369358,2020-06-10,08009f,1,4,5,2,5,5,4,2,...,2,2,2,1,99,3,99,México,99,2
369359,2020-06-10,077eca,2,12,15,1,9,15,81,1,...,2,2,2,2,1,3,99,México,99,97
369360,2020-06-10,16b2f3,2,12,27,1,20,27,15,1,...,2,1,2,2,1,3,99,México,99,97
369361,2020-06-10,15aafe,1,4,25,2,25,25,11,1,...,2,2,2,2,99,3,99,México,99,97

In [11]:
data.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'DIABETES',
       'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'RESULTADO', 'MIGRANTE', 'PAIS_NACIONALIDAD',
       'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [12]:
data["SECTOR"]

0          3
1          3
2          4
3          4
4          4
          ..
369357    12
369358     4
369359    12
369360    12
369361     4
Name: SECTOR, Length: 369362, dtype: int64