### Bibliotecas

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [48]:
#Confirmados
data = pd.read_csv("../datasets/cvid.csv")

# Acomodando el DF

In [56]:
data.head(4)

,cve_ent,poblacion,nombre,12-01-2020,13-01-2020,14-01-2020,15-01-2020,16-01-2020,17-01-2020,18-01-2020,...,26-10-2020,27-10-2020,28-10-2020,29-10-2020,30-10-2020,31-10-2020,01-11-2020,02-11-2020,03-11-2020,04-11-2020
0,1,1434635,AGUASCALIENTES,0,0,0,0,0,0,0,...,139,136,93,59,70,37,21,30,0,2
1,2,3634868,BAJA CALIFORNIA,0,0,0,0,0,0,0,...,153,96,58,45,36,25,9,31,34,16
2,3,804708,BAJA CALIFORNIA SUR,0,0,0,0,0,0,0,...,111,91,70,60,57,32,20,53,34,0
3,4,1000617,CAMPECHE,0,0,0,0,0,0,0,...,28,13,18,6,15,1,0,3,1,1

In [154]:
df = data.T
df

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
cve_ent,1,2,3,4,7,8,9,5,6,10,...,24,25,26,27,28,29,30,31,32,0
poblacion,1434635,3634868,804708,1000617,5730367,3801487,9018645,3218720,785153,1868996,...,2866142,3156674,3074745,2572287,3650602,1380011,8539862,2259098,1666426,127792286
nombre,AGUASCALIENTES,BAJA CALIFORNIA,BAJA CALIFORNIA SUR,CAMPECHE,CHIAPAS,CHIHUAHUA,DISTRITO FEDERAL,COAHUILA,COLIMA,DURANGO,...,SAN LUIS POTOSI,SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS,Nacional
12-01-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13-01-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31-10-2020,37,25,32,1,1,28,118,118,9,61,...,81,19,19,38,37,10,27,45,87,1675
01-11-2020,21,9,20,0,1,18,97,64,11,51,...,42,13,20,30,26,13,24,30,54,1147
02-11-2020,30,31,53,3,3,10,151,133,10,224,...,7,26,29,38,34,12,23,64,158,2279
03-11-2020,0,34,34,1,3,6,102,159,8,211,...,6,22,30,97,14,7,5,63,185,1865
04-11-2020,2,16,0,1,0,14,24,29,1,7,...,3,5,8,46,3,0,3,12,45,367

In [156]:
date = df.index[3:]
date

Index(['12-01-2020', '13-01-2020', '14-01-2020', '15-01-2020', '16-01-2020',
       '17-01-2020', '18-01-2020', '19-01-2020', '20-01-2020', '21-01-2020',
       ...
       '26-10-2020', '27-10-2020', '28-10-2020', '29-10-2020', '30-10-2020',
       '31-10-2020', '01-11-2020', '02-11-2020', '03-11-2020', '04-11-2020'],
      dtype='object', length=298)

In [169]:
col = df.iloc[2]
col

0          AGUASCALIENTES
1         BAJA CALIFORNIA
2     BAJA CALIFORNIA SUR
3                CAMPECHE
4                 CHIAPAS
5               CHIHUAHUA
6        DISTRITO FEDERAL
7                COAHUILA
8                  COLIMA
9                 DURANGO
10             GUANAJUATO
11               GUERRERO
12                HIDALGO
13                JALISCO
14                 MEXICO
15              MICHOACAN
16                MORELOS
17                NAYARIT
18             NUEVO LEON
19                 OAXACA
20                 PUEBLA
21              QUERETARO
22           QUINTANA ROO
23        SAN LUIS POTOSI
24                SINALOA
25                 SONORA
26                TABASCO
27             TAMAULIPAS
28               TLAXCALA
29               VERACRUZ
30                YUCATAN
31              ZACATECAS
32               Nacional
Name: nombre, dtype: object

In [174]:
d = pd.DataFrame(df, index=date)

In [180]:
d.columns = ['AGUASCALIENTES', 'BAJA CALIFORNIA', 'BAJA CALIFORNIA SUR','CAMPECHE','CHIAPAS', 'CHIHUAHUA','DISTRITO FEDERAL',
            'COAHUILA','COLIMA', 'DURANGO','GUANAJUATO', 'GUERRERO','HIDALGO','JALISCO','MEXICO','MICHOACAN','MORELOS',
            'NAYARIT','NUEVO LEON','OAXACA','PUEBLA','QUERETARO','QUINTANA ROO'
        ,'SAN LUIS POTOSI'
                ,'SINALOA'
                 ,'SONORA'
                ,'TABASCO'
             ,'TAMAULIPAS'
               ,'TLAXCALA'
               ,'VERACRUZ'
                ,'YUCATAN'
              ,'ZACATECAS'
               ,'Nacional']

In [182]:
dtf = d.copy()

In [183]:
dtf

,AGUASCALIENTES,BAJA CALIFORNIA,BAJA CALIFORNIA SUR,CAMPECHE,CHIAPAS,CHIHUAHUA,DISTRITO FEDERAL,COAHUILA,COLIMA,DURANGO,...,SAN LUIS POTOSI,SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS,Nacional
12-01-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13-01-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
14-01-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
15-01-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16-01-2020,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31-10-2020,37,25,32,1,1,28,118,118,9,61,...,81,19,19,38,37,10,27,45,87,1675
01-11-2020,21,9,20,0,1,18,97,64,11,51,...,42,13,20,30,26,13,24,30,54,1147
02-11-2020,30,31,53,3,3,10,151,133,10,224,...,7,26,29,38,34,12,23,64,158,2279
03-11-2020,0,34,34,1,3,6,102,159,8,211,...,6,22,30,97,14,7,5,63,185,1865
04-11-2020,2,16,0,1,0,14,24,29,1,7,...,3,5,8,46,3,0,3,12,45,367

In [185]:
dtf.index = pd.to_datetime(dtf.index, dayfirst=True)

In [191]:
dtf.describe()

,AGUASCALIENTES,BAJA CALIFORNIA,BAJA CALIFORNIA SUR,CAMPECHE,CHIAPAS,CHIHUAHUA,DISTRITO FEDERAL,COAHUILA,COLIMA,DURANGO,...,SAN LUIS POTOSI,SINALOA,SONORA,TABASCO,TAMAULIPAS,TLAXCALA,VERACRUZ,YUCATAN,ZACATECAS,Nacional
count,298,298,298,298,298,298,298,298,298,298,...,298,298,298,298,298,298,298,298,298,298
unique,97,141,119,79,88,129,226,168,72,117,...,153,142,178,163,163,86,165,147,108,243
top,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
freq,71,62,69,80,74,63,50,65,90,78,...,70,64,66,67,68,77,66,65,79,43