En esta notebook, se implementa: 
- **Extract**: Extraccion de los ficheros de tipos csv, de las diferentes fuentes.
- **Transform** : Transformacion de los datos que estan en los ficheros csv, asi como incorporar nuevos datos utilies.
- **Load** : En este repositorio, no se cargara a ninguna Data lake o Warehouse, solo dejaremos los datos preparados para su analisis.

In [19]:
#Importando las libreerias a usar
import pandas as pd
import numpy as np
import json

# **Extract**

In [53]:
df_nacional = pd.read_csv('../../datasets/Casos_covid.csv')
df_municipal = pd.read_csv('../../datasets/Casos_Diarios_Municipio_.csv')

In [51]:
#Datos nivel nacional
df_nacional.head(5)

,cve_ent,poblacion,nombre,26-02-2020,27-02-2020,28-02-2020,29-02-2020,01-03-2020,02-03-2020,03-03-2020,...,23-11-2021,24-11-2021,25-11-2021,26-11-2021,27-11-2021,28-11-2021,29-11-2021,30-11-2021,01-12-2021,02-12-2021
0,1,1434635,AGUASCALIENTES,0,0,0,0,0,0,0,...,71,78,69,67,13,15,57,41,29,0
1,2,3634868,BAJA CALIFORNIA,0,0,0,0,0,0,0,...,510,495,422,369,116,128,483,409,175,1
2,3,804708,BAJA CALIFORNIA SUR,0,0,0,0,0,0,0,...,58,51,50,54,26,17,56,49,27,0
3,4,1000617,CAMPECHE,0,0,0,0,0,0,0,...,9,7,5,4,1,3,5,1,1,0
4,7,5730367,CHIAPAS,0,0,0,1,0,0,0,...,8,2,2,2,0,0,5,1,3,0

In [14]:
#Datos por municipio
df_municipal.head(5)

,cve_ent,poblacion,nombre,26-02-2020,27-02-2020,28-02-2020,29-02-2020,01-03-2020,02-03-2020,03-03-2020,...,23-11-2021,24-11-2021,25-11-2021,26-11-2021,27-11-2021,28-11-2021,29-11-2021,30-11-2021,01-12-2021,02-12-2021
0,16046,15290,Juarez,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,16047,22358,Jungapeo,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,16048,5862,Lagunillas,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,16049,18769,Madero,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5035,744247,Torreon,0,0,1,0,0,0,0,...,40,43,29,26,20,19,36,33,16,0

In [235]:
#Coordenadas de  estados
with open('./../../datasets/cord.json', 'r', encoding='utf-8') as file:
    coordenada = file.read()

coordenada = json.loads(coordenada)
coordenada

[{'Estado': 'Aguascalientes', 'Latitud': 21.8833, 'Longitud': -102.3167},
 {'Estado': 'Baja California', 'Latitud': 32.62781, 'Longitud': -115.45446},
 {'Estado': 'Baja California Sur', 'Latitud': 25.0333, 'Longitud': -111.7333},
 {'Estado': 'Campeche', 'Latitud': 19.8, 'Longitud': -90.5},
 {'Estado': 'Chiapas', 'Latitud': 16.8, 'Longitud': -92.8},
 {'Estado': 'Chihuahua', 'Latitud': 28.63528, 'Longitud': -106.08889},
 {'Estado': 'Coahuila', 'Latitud': 25.42321, 'Longitud': -101.0053},
 {'Estado': 'Colima', 'Latitud': 19.2333, 'Longitud': -103.7},
 {'Estado': ' Distrito Federal', 'Latitud': 19.42847, 'Longitud': -99.12766},
 {'Estado': 'Durango', 'Latitud': 24.0333, 'Longitud': -104.65},
 {'Estado': 'Estado de Mexico', 'Latitud': 19.4333, 'Longitud': -99.1333},
 {'Estado': 'Guanajuato', 'Latitud': 21.0333, 'Longitud': -101.25},
 {'Estado': 'Guerrero', 'Latitud': 17.5833, 'Longitud': -99.6667},
 {'Estado': 'Hidalgo', 'Latitud': 20.0333, 'Longitud': -98.7},
 {'Estado': 'Jalisco', 'Latitud': 20.66682, 'Longitud': -103.39182},
 {'Estado': 'Michoacan', 'Latitud': 19.70078, 'Longitud': -101.18443},
 {'Estado': 'Morelos', 'Latitud': 18.8, 'Longitud': -99.25},
 {'Estado': 'Nayarit', 'Latitud': 21.0333, 'Longitud': -104.9},
 {'Estado': 'Nuevo Leon', 'Latitud': 25.67507, 'Longitud': -100.31847},
 {'Estado': 'Oaxaca', 'Latitud': 17.05, 'Longitud': -96.7167},
 {'Estado': 'Puebla', 'Latitud': 19.03793, 'Longitud': -98.20346},
 {'Estado': 'Queretaro', 'Latitud': 20.6333, 'Longitud': -100.3833},
 {'Estado': 'Quintana Roo', 'Latitud': 20.4333, 'Longitud': -86.9167},
 {'Estado': 'San Luis Potosi', 'Latitud': 22.14982, 'Longitud': -100.97916},
 {'Estado': 'Sinaloa', 'Latitud': 24.15, 'Longitud': -107.4},
 {'Estado': 'Sonora', 'Latitud': 29.1026, 'Longitud': -110.97732},
 {'Estado': 'Tabasco', 'Latitud': 16.65, 'Longitud': -93.5167},
 {'Estado': 'Tamaulipas', 'Latitud': 23.0333, 'Longitud': -98.15},
 {'Estado': 'Tlaxcala', 'Latitud': 19.3, 'Longitud': -98.9},
 {'Estado': 'Veracruz', 'Latitud': 19.1833, 'Longitud': -96.1333},
 {'Estado': 'Yucatan', 'Latitud': 20.97537, 'Longitud': -89.61696},
 {'Estado': 'Zacatecas', 'Latitud': 22.7333, 'Longitud': -102.5}]

# Transform

In [154]:
""" Llamamos a la funcion para generar dataframe """
%run './../funciones/Function_where.ipynb'

In [201]:
""" Cambiando de nombre una columna"""
df_nacional.rename(columns={'nombre':'Estado'}, inplace=True)
df_nacional.head(3)

,cve_ent,poblacion,Estado,26-02-2020,27-02-2020,28-02-2020,29-02-2020,01-03-2020,02-03-2020,03-03-2020,...,23-11-2021,24-11-2021,25-11-2021,26-11-2021,27-11-2021,28-11-2021,29-11-2021,30-11-2021,01-12-2021,02-12-2021
0,1,1434635,AGUASCALIENTES,0,0,0,0,0,0,0,...,71,78,69,67,13,15,57,41,29,0
1,2,3634868,BAJA CALIFORNIA,0,0,0,0,0,0,0,...,510,495,422,369,116,128,483,409,175,1
2,3,804708,BAJA CALIFORNIA SUR,0,0,0,0,0,0,0,...,58,51,50,54,26,17,56,49,27,0

In [202]:
df_nacional.head(3)

,cve_ent,poblacion,Estado,26-02-2020,27-02-2020,28-02-2020,29-02-2020,01-03-2020,02-03-2020,03-03-2020,...,23-11-2021,24-11-2021,25-11-2021,26-11-2021,27-11-2021,28-11-2021,29-11-2021,30-11-2021,01-12-2021,02-12-2021
0,1,1434635,AGUASCALIENTES,0,0,0,0,0,0,0,...,71,78,69,67,13,15,57,41,29,0
1,2,3634868,BAJA CALIFORNIA,0,0,0,0,0,0,0,...,510,495,422,369,116,128,483,409,175,1
2,3,804708,BAJA CALIFORNIA SUR,0,0,0,0,0,0,0,...,58,51,50,54,26,17,56,49,27,0

In [236]:
""" Pasando a mayusculas todas los estados """
df_coordenada = pd.DataFrame(coordenada)
estado = [ w.upper() for w in df_coordenada.Estado]
df_coordenada['Estado'] = estado
df_coordenada.head(4)

                Estado   Latitud   Longitud
0       AGUASCALIENTES  21.88330 -102.31670
1      BAJA CALIFORNIA  32.62781 -115.45446
2  BAJA CALIFORNIA SUR  25.03330 -111.73330
3             CAMPECHE  19.80000  -90.50000

In [242]:
""" Probando una merge con 2 tablas """
pd.concat([df_coordenada.sort_values(by='Estado'), df_nacional.sort_values(by='Estado')], axis=1)

,Estado,Latitud,Longitud,cve_ent,poblacion,Estado,26-02-2020,27-02-2020,28-02-2020,29-02-2020,...,23-11-2021,24-11-2021,25-11-2021,26-11-2021,27-11-2021,28-11-2021,29-11-2021,30-11-2021,01-12-2021,02-12-2021
0,AGUASCALIENTES,21.88330,-102.31670,1,1434635,AGUASCALIENTES,0,0,0,0,...,71,78,69,67,13,15,57,41,29,0
1,BAJA CALIFORNIA,32.62781,-115.45446,2,3634868,BAJA CALIFORNIA,0,0,0,0,...,510,495,422,369,116,128,483,409,175,1
2,BAJA CALIFORNIA SUR,25.03330,-111.73330,3,804708,BAJA CALIFORNIA SUR,0,0,0,0,...,58,51,50,54,26,17,56,49,27,0
3,CAMPECHE,19.80000,-90.50000,4,1000617,CAMPECHE,0,0,0,0,...,9,7,5,4,1,3,5,1,1,0
4,CHIAPAS,16.80000,-92.80000,7,5730367,CHIAPAS,0,0,0,1,...,8,2,2,2,0,0,5,1,3,0
5,CHIHUAHUA,28.63528,-106.08889,8,3801487,CHIHUAHUA,0,0,0,0,...,242,219,225,205,65,52,291,215,76,0
6,COAHUILA,25.42321,-101.00530,9,9018645,DISTRITO FEDERAL,0,2,0,0,...,366,333,399,323,162,71,336,273,152,2
7,COLIMA,19.23330,-103.70000,5,3218720,COAHUILA,0,0,1,0,...,178,184,143,128,60,66,180,158,81,1
8,DISTRITO FEDERAL,19.42847,-99.12766,6,785153,COLIMA,0,0,0,0,...,10,7,3,3,2,3,2,4,0,0
9,DURANGO,24.03330,-104.65000,10,1868996,DURANGO,0,0,0,0,...,65,42,40,45,11,15,87,27,25,0
10,ESTADO DE MEXICO,19.43330,-99.13330,11,6228175,GUANAJUATO,0,0,0,0,...,313,239,204,209,74,54,277,207,108,1
11,GUANAJUATO,21.03330,-101.25000,12,3657048,GUERRERO,0,0,0,0,...,25,19,17,10,1,6,17,8,5,0
12,GUERRERO,17.58330,-99.66670,13,3086414,HIDALGO,0,1,0,0,...,26,15,12,13,7,5,13,15,7,0
13,HIDALGO,20.03330,-98.70000,14,8409693,JALISCO,0,0,0,0,...,72,98,73,67,17,32,85,70,38,0
14,JALISCO,20.66682,-103.39182,15,17427790,MEXICO,0,1,1,1,...,163,153,171,112,34,40,130,84,46,4
15,MICHOACAN,19.70078,-101.18443,16,4825401,MICHOACAN,0,0,0,0,...,18,14,15,21,11,9,19,5,3,0
16,MORELOS,18.80000,-99.25000,17,2044058,MORELOS,0,0,0,0,...,18,19,20,25,9,15,18,6,4,0
17,NAYARIT,21.03330,-104.90000,18,1288571,NAYARIT,0,0,0,0,...,11,9,7,6,4,5,8,7,5,0
18,NUEVO LEON,25.67507,-100.31847,19,5610153,NUEVO LEON,0,0,0,0,...,102,112,99,85,15,25,102,78,45,0
19,OAXACA,17.05000,-96.71670,20,4143593,OAXACA,0,0,0,0,...,24,26,42,29,9,5,21,31,10,0
20,PUEBLA,19.03793,-98.20346,21,6604451,PUEBLA,0,0,0,0,...,196,139,105,25,9,21,21,18,15,1
21,QUERETARO,20.63330,-100.38330,22,2279637,QUERETARO,0,0,0,0,...,62,67,42,36,15,25,49,56,22,0
22,QUINTANA ROO,20.43330,-86.91670,23,1723259,QUINTANA ROO,0,0,0,0,...,8,6,7,11,7,4,3,4,5,0
23,SAN LUIS POTOSI,22.14982,-100.97916,24,2866142,SAN LUIS POTOSI,0,0,0,0,...,76,70,65,65,35,25,69,48,14,0
24,SINALOA,24.15000,-107.40000,25,3156674,SINALOA,0,0,0,0,...,40,51,40,39,12,19,44,27,18,0
25,SONORA,29.10260,-110.97732,26,3074745,SONORA,0,0,0,0,...,268,269,237,205,85,95,273,209,110,1
26,TABASCO,16.65000,-93.51670,27,2572287,TABASCO,0,0,0,0,...,21,28,20,31,12,4,30,33,3,1
27,TAMAULIPAS,23.03330,-98.15000,28,3650602,TAMAULIPAS,0,0,0,0,...,45,46,37,34,17,14,52,31,8,0
28,TLAXCALA,19.30000,-98.90000,29,1380011,TLAXCALA,0,0,0,0,...,7,5,8,5,3,4,7,1,0,0
29,VERACRUZ,19.18330,-96.13330,30,8539862,VERACRUZ,0,0,0,0,...,28,18,18,20,7,1,18,17,6,0
30,YUCATAN,20.97537,-89.61696,31,2259098,YUCATAN,0,0,0,0,...,42,58,28,33,9,5,41,25,25,0
31,ZACATECAS,22.73330,-102.50000,32,1666426,ZACATECAS,0,0,0,0,...,33,23,9,12,3,5,31,8,20,0
32,NaN,NaN,NaN,0,127792286,Nacional,0,4,2,2,...,3115,2902,2634,2293,851,788,2830,2166,1086,12

In [239]:
pd.merge(df_coordenada.sort_values(by='Estado'), df_nacional.sort_values(by='Estado'))

,Estado,Latitud,Longitud,cve_ent,poblacion,26-02-2020,27-02-2020,28-02-2020,29-02-2020,01-03-2020,...,23-11-2021,24-11-2021,25-11-2021,26-11-2021,27-11-2021,28-11-2021,29-11-2021,30-11-2021,01-12-2021,02-12-2021
0,AGUASCALIENTES,21.88330,-102.31670,1,1434635,0,0,0,0,0,...,71,78,69,67,13,15,57,41,29,0
1,BAJA CALIFORNIA,32.62781,-115.45446,2,3634868,0,0,0,0,0,...,510,495,422,369,116,128,483,409,175,1
2,BAJA CALIFORNIA SUR,25.03330,-111.73330,3,804708,0,0,0,0,0,...,58,51,50,54,26,17,56,49,27,0
3,CAMPECHE,19.80000,-90.50000,4,1000617,0,0,0,0,0,...,9,7,5,4,1,3,5,1,1,0
4,CHIAPAS,16.80000,-92.80000,7,5730367,0,0,0,1,0,...,8,2,2,2,0,0,5,1,3,0
5,CHIHUAHUA,28.63528,-106.08889,8,3801487,0,0,0,0,0,...,242,219,225,205,65,52,291,215,76,0
6,COAHUILA,25.42321,-101.00530,5,3218720,0,0,1,0,0,...,178,184,143,128,60,66,180,158,81,1
7,COLIMA,19.23330,-103.70000,6,785153,0,0,0,0,0,...,10,7,3,3,2,3,2,4,0,0
8,DURANGO,24.03330,-104.65000,10,1868996,0,0,0,0,0,...,65,42,40,45,11,15,87,27,25,0
9,GUANAJUATO,21.03330,-101.25000,11,6228175,0,0,0,0,1,...,313,239,204,209,74,54,277,207,108,1
10,GUERRERO,17.58330,-99.66670,12,3657048,0,0,0,0,0,...,25,19,17,10,1,6,17,8,5,0
11,HIDALGO,20.03330,-98.70000,13,3086414,0,1,0,0,0,...,26,15,12,13,7,5,13,15,7,0
12,JALISCO,20.66682,-103.39182,14,8409693,0,0,0,0,0,...,72,98,73,67,17,32,85,70,38,0
13,MICHOACAN,19.70078,-101.18443,16,4825401,0,0,0,0,0,...,18,14,15,21,11,9,19,5,3,0
14,MORELOS,18.80000,-99.25000,17,2044058,0,0,0,0,0,...,18,19,20,25,9,15,18,6,4,0
15,NAYARIT,21.03330,-104.90000,18,1288571,0,0,0,0,0,...,11,9,7,6,4,5,8,7,5,0
16,NUEVO LEON,25.67507,-100.31847,19,5610153,0,0,0,0,0,...,102,112,99,85,15,25,102,78,45,0
17,OAXACA,17.05000,-96.71670,20,4143593,0,0,0,0,1,...,24,26,42,29,9,5,21,31,10,0
18,PUEBLA,19.03793,-98.20346,21,6604451,0,0,0,0,0,...,196,139,105,25,9,21,21,18,15,1
19,QUERETARO,20.63330,-100.38330,22,2279637,0,0,0,0,0,...,62,67,42,36,15,25,49,56,22,0
20,QUINTANA ROO,20.43330,-86.91670,23,1723259,0,0,0,0,0,...,8,6,7,11,7,4,3,4,5,0
21,SAN LUIS POTOSI,22.14982,-100.97916,24,2866142,0,0,0,0,0,...,76,70,65,65,35,25,69,48,14,0
22,SINALOA,24.15000,-107.40000,25,3156674,0,0,0,0,0,...,40,51,40,39,12,19,44,27,18,0
23,SONORA,29.10260,-110.97732,26,3074745,0,0,0,0,0,...,268,269,237,205,85,95,273,209,110,1
24,TABASCO,16.65000,-93.51670,27,2572287,0,0,0,0,0,...,21,28,20,31,12,4,30,33,3,1
25,TAMAULIPAS,23.03330,-98.15000,28,3650602,0,0,0,0,0,...,45,46,37,34,17,14,52,31,8,0
26,TLAXCALA,19.30000,-98.90000,29,1380011,0,0,0,0,0,...,7,5,8,5,3,4,7,1,0,0
27,VERACRUZ,19.18330,-96.13330,30,8539862,0,0,0,0,0,...,28,18,18,20,7,1,18,17,6,0
28,YUCATAN,20.97537,-89.61696,31,2259098,0,0,0,0,0,...,42,58,28,33,9,5,41,25,25,0
29,ZACATECAS,22.73330,-102.50000,32,1666426,0,0,0,0,0,...,33,23,9,12,3,5,31,8,20,0

In [243]:
""" Guardando el merge de 2 tablas"""
df_completo = pd.merge(df_coordenada.sort_values(by='Estado'), df_nacional.sort_values(by='Estado'))
df_completo.head(4)

,Estado,Latitud,Longitud,cve_ent,poblacion,26-02-2020,27-02-2020,28-02-2020,29-02-2020,01-03-2020,...,23-11-2021,24-11-2021,25-11-2021,26-11-2021,27-11-2021,28-11-2021,29-11-2021,30-11-2021,01-12-2021,02-12-2021
0,AGUASCALIENTES,21.88330,-102.31670,1,1434635,0,0,0,0,0,...,71,78,69,67,13,15,57,41,29,0
1,BAJA CALIFORNIA,32.62781,-115.45446,2,3634868,0,0,0,0,0,...,510,495,422,369,116,128,483,409,175,1
2,BAJA CALIFORNIA SUR,25.03330,-111.73330,3,804708,0,0,0,0,0,...,58,51,50,54,26,17,56,49,27,0
3,CAMPECHE,19.80000,-90.50000,4,1000617,0,0,0,0,0,...,9,7,5,4,1,3,5,1,1,0

In [255]:
"""Total de datos faltantes"""
df_completo.isna().sum()

Estado        0
Latitud       0
Longitud      0
cve_ent       0
poblacion     0
             ..
28-11-2021    0
29-11-2021    0
30-11-2021    0
01-12-2021    0
02-12-2021    0
Length: 651, dtype: int64

# LOAD

#### En la carga, solo se guardara en un fichero de tipo csv, aunque podria usarse un data warehouse. Pero para el fin del repositorio no sera tan necesario.

In [258]:
df_completo.to_csv('./data_complete.csv', index=False)

- Para el primer caso, se implementara un analisis descriptivo de los datos.
- Para el segundo caso, un dashboard en Power BI