En esta notebook, se implementa: 
- **Extract**: Extraccion de los ficheros de tipos csv, de las diferentes fuentes.
- **Transform** : Transformacion de los datos que estan en los ficheros csv, asi como incorporar nuevos datos utilies.
- **Load** : En este repositorio, no se cargara a ninguna Data lake o Warehouse, solo dejaremos los datos preparados para su analisis.

In [19]:
#Importando las libreerias a usar
import pandas as pd
import numpy as np
import json

# **Extract**

In [11]:
df_nacional = pd.read_csv('../../datasets/Casos_covid.csv')
df_municipal = pd.read_csv('../../datasets/Casos_Diarios_Municipio_.csv')

In [12]:
#Datos nivel nacional
df_nacional.head(5)

,cve_ent,poblacion,nombre,26-02-2020,27-02-2020,28-02-2020,29-02-2020,01-03-2020,02-03-2020,03-03-2020,...,23-11-2021,24-11-2021,25-11-2021,26-11-2021,27-11-2021,28-11-2021,29-11-2021,30-11-2021,01-12-2021,02-12-2021
0,1,1434635,AGUASCALIENTES,0,0,0,0,0,0,0,...,71,78,69,67,13,15,57,41,29,0
1,2,3634868,BAJA CALIFORNIA,0,0,0,0,0,0,0,...,510,495,422,369,116,128,483,409,175,1
2,3,804708,BAJA CALIFORNIA SUR,0,0,0,0,0,0,0,...,58,51,50,54,26,17,56,49,27,0
3,4,1000617,CAMPECHE,0,0,0,0,0,0,0,...,9,7,5,4,1,3,5,1,1,0
4,7,5730367,CHIAPAS,0,0,0,1,0,0,0,...,8,2,2,2,0,0,5,1,3,0

In [14]:
#Datos por municipio
df_municipal.head(5)

,cve_ent,poblacion,nombre,26-02-2020,27-02-2020,28-02-2020,29-02-2020,01-03-2020,02-03-2020,03-03-2020,...,23-11-2021,24-11-2021,25-11-2021,26-11-2021,27-11-2021,28-11-2021,29-11-2021,30-11-2021,01-12-2021,02-12-2021
0,16046,15290,Juarez,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,16047,22358,Jungapeo,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2,16048,5862,Lagunillas,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,16049,18769,Madero,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,5035,744247,Torreon,0,0,1,0,0,0,0,...,40,43,29,26,20,19,36,33,16,0

In [39]:
l={}
with open('./../../datasets/cord.json', 'r', encoding='utf-8') as file:
    coordenada = file.read()

print(coordenada)

[
    {
        "Estado": "Aguascalientes",
        "Latitud": 21.8833,
        "Longitud": -102.3167
    },
    {
        "Estado": "Baja California",
        "Latitud": 	32.62781,
        "Longitud": -115.45446
    },
    {
        "Estado": "Baja California Sur",
        "Latitud": 25.0333,
        "Longitud": -111.7333
    },
    {
        "Estado": "Campeche",
        "Latitud": 19.8,
        "Longitud": -90.5
    },
    {
        "Estado": "Chiapas",
        "Latitud": 16.8,
        "Longitud": -92.8
    },
    {
        "Estado": "Chihuahua",
        "Latitud": 28.63528,
        "Longitud": -106.08889
    },
    {
        "Estado": "Coahuila",
        "Latitud": 25.42321,
        "Longitud": -101.0053
    },
    {
        "Estado": "Colima",
        "Latitud": 19.2333,
        "Longitud": -103.7
    },
    {
        "Estado": "Durango",
        "Latitud": 24.0333,
        "Longitud": -104.65
    },
    {
        "Estado": "Estado de Mexico",
        "Latitud": 19.4333,
        "Longitud": -99.1333
    },
    {
        "Estado": "Guanajuato",
        "Latitud": 21.0333,
        "Longitud": -101.25
    },
    {
        "Estado": "Guerrero",
        "Latitud": 17.5833,
        "Longitud": -99.6667
    },
    {
        "Estado": "Hidalgo",
        "Latitud": 20.0333,
        "Longitud": -98.7
    },
    {
        "Estado": "Jalisco",
        "Latitud": 20.66682,
        "Longitud": -103.39182
    },
    {
        "Estado": "Michoacan",
        "Latitud": 	19.70078,
        "Longitud": -101.18443
    },
    {
        "Estado": "Morelos",
        "Latitud": 18.8,
        "Longitud": -99.25
    },
    {
        "Estado": "Nayarit",
        "Latitud": 21.0333,
        "Longitud": -104.9
    },
    {
        "Estado": "Nuevo Leon",
        "Latitud": 	25.67507,
        "Longitud": -100.31847
    },
    {
        "Estado": "Oaxaca",
        "Latitud": 17.05,
        "Longitud": -96.7167
    },
    {
        "Estado": "Puebla",
        "Latitud": 19.03793,
        "Longitud": -98.20346
    },
    {
        "Estado": "Queretaro",
        "Latitud": 20.6333,
        "Longitud": -100.3833
    },
    {
        "Estado": "Quintana Roo",
        "Latitud": 20.4333,
        "Longitud": -86.9167
    },
    {
        "Estado": "San Luis Potosi",
        "Latitud": 	22.14982,
        "Longitud": -100.97916
    },
    {
        "Estado": "Sinaloa",
        "Latitud": 24.15,
        "Longitud": -107.4
    },
    {
        "Estado": "Sonora",
        "Latitud": 29.1026,
        "Longitud": -110.97732
    },
    {
        "Estado": "Tabasco",
        "Latitud": 16.65,
        "Longitud": -93.5167
    },
    {
        "Estado": "Tamaulipas",
        "Latitud": 23.0333,
        "Longitud": -98.15
    },
    {
        "Estado": "Tlaxcala",
        "Latitud": 19.3,
        "Longitud": -98.9
    },
    {
        "Estado": "Veracruz",
        "Latitud": 19.1833,
        "Longitud": -96.1333
    },
    {
        "Estado": "Yucatan",
        "Latitud": 	20.97537,
        "Longitud": -89.61696
    },
    {
        "Estado": "Zacatecas",
        "Latitud": 22.7333,
        "Longitud": -102.5
    },
    {
        "Estado": "Ciudad de Mexico",
        "Latitud": 19.42847,
        "Longitud": -99.12766
    }
]

# Transform